workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "api"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never

stages:
  - build

docker_image_alma10:
  stage: build
  image: quay.io/buildah/stable
  variables:
    BUILDAH_FORMAT: docker
  script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - buildah bud --file "${CI_PROJECT_DIR}/alma-10/Dockerfile" --tag "${CI_REGISTRY_IMAGE}/alma-10-build:${CI_COMMIT_SHORT_SHA}" "${CI_PROJECT_DIR}/alma-10"
    - buildah push "${CI_REGISTRY_IMAGE}/alma-10-build:${CI_COMMIT_SHORT_SHA}"
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        buildah tag "${CI_REGISTRY_IMAGE}/alma-10-build:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}/alma-10-build:latest"
        buildah push "${CI_REGISTRY_IMAGE}/alma-10-build:latest"
      fi
